# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-IKC
version:      0.2303
version_from: IKC.pm
installdirs:  site
requires:
    POE:                           1.311
    Scalar::Util:                  1
    Test::More:                    0.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
