--- #YAML:1.0
name:               POE-Component-IKC
version:            0.2300
abstract:           Inter-Kernel Communication for POE
author:
    - Philip Gwyn
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:           1.311
    Scalar::Util:  1
    Test::More:    0.6
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
